# UNIX shell (command interpreter)
brew "zsh"
vscode "akamud.vscode-theme-onedark"
vscode "esbenp.prettier-vscode"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "psycha0s.cpp-format"
vscode "twxs.cmake"
vscode "usernamehw.errorlens"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscode-icons-team.vscode-icons"
vscode "zhuangtongfa.material-theme"
