#!/usr/bin/env bash


# List of packages to install
packages=(
    zsh
    stow
    tmux
    git
    vim
    build-essential
    curl 
    i3
    i3lock
    xautolock
    pulseaudio
    playerctl
    feh
    picom
    network-manager
    network-manager-gnome
    polybar
    maim
    xdotool
    nsxiv
    fd-find
    ripgrep
    python3
    pip
    lua5.1
    liblua5.1-dev
    nodejs
    npm
)
# Update and install
echo "Updating package list..."
sudo apt update

echo "Installing packages: ${packages[*]}"
sudo apt install -y "${packages[@]}"

# HOMEBREW
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# GHOSTTY
# Download the latest AppImage package from releases
wget https://github.com/pkgforge-dev/ghostty-appimage/releases/download/${VERSION}/Ghostty-${VERSION}-${ARCH}.AppImage
# Make the AppImage executable
chmod +x Ghostty-${VERSION}-${ARCH}.AppImage
# Run the AppImage
./Ghostty-${VERSION}-${ARCH}.AppImage
# Run the AppImage
./Ghostty-${VERSION}-${ARCH}.AppImage


# NVIM
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
